service: s3-data-processing
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9

constructs:
  jobs:
    type: queue
    worker:
      handler: handler.consumer

plugins:
  - serverless-lift
  - serverless-python-requirements
  - serverless-offline

package:
  patterns:
    - "!node_modules/**"
